#!/usr/bin/env python3
"""Generate ANTLR4 parser files from the .g4 grammars.

Usage:
    python scripts/gen_antlr.py          # generate into src/lm/cobol/gen/
    python scripts/gen_antlr.py --check  # just verify antlr4 is installed
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
GRAMMARS = ROOT / "grammars"
COBOL_OUT = ROOT / "src" / "lm" / "cobol" / "gen"
JCL_OUT = ROOT / "src" / "lm" / "jcl" / "gen"


def _find_antlr_jar() -> Path | None:
    """Look for antlr-*.jar in common locations."""
    candidates = [
        Path.home() / ".m2" / "repository" / "org" / "antlr",
        Path("/usr/local/lib"),
        Path("/opt/antlr"),
        ROOT / "tools",
    ]
    for base in candidates:
        for jar in base.rglob("antlr*-complete.jar"):
            return jar
    return None


def generate(grammar: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    # Try antlr4 tool directly (installed via pip antlr4-tools)
    tool = shutil.which("antlr4")
    if tool:
        cmd = [tool, "-Dlanguage=Python3", "-visitor", "-o", str(output_dir), str(grammar)]
    else:
        # Fall back to java -jar
        jar = _find_antlr_jar()
        if not jar:
            print(
                "ERROR: antlr4 not found. Install with:\n"
                "  pip install antlr4-tools\n"
                "or download the complete jar from https://www.antlr.org",
                file=sys.stderr,
            )
            sys.exit(1)
        cmd = [
            "java", "-jar", str(jar),
            "-Dlanguage=Python3", "-visitor",
            "-o", str(output_dir),
            str(grammar),
        ]

    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)

    # Write __init__.py so the gen/ package is importable
    init = output_dir / "__init__.py"
    if not init.exists():
        init.write_text("# generated by scripts/gen_antlr.py\n")
    print(f"  → {output_dir}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="Only check tool availability")
    args = ap.parse_args()

    if args.check:
        tool = shutil.which("antlr4")
        if tool:
            print(f"antlr4 found: {tool}")
        else:
            jar = _find_antlr_jar()
            if jar:
                print(f"antlr4 jar found: {jar}")
            else:
                print("antlr4 NOT found — run: pip install antlr4-tools")
                sys.exit(1)
        return

    generate(GRAMMARS / "Cobol85.g4", COBOL_OUT)
    generate(GRAMMARS / "JCL.g4", JCL_OUT)
    print("Done.")


if __name__ == "__main__":
    main()
